name: auto_scroll_image
description: "By integrating Auto Scroll Image, you gain the capability to effortlessly incorporate scrolling advertisements tailored to your app's content. 
Moreover, it is compatible with iOS, Android, macOS, and web platforms, offering a seamless scrolling experience across a diverse range of devices, "
repository: "https://github.com/johnhcolani/AutoScrollImagePackage.git"
version: 0.2.8-dev
author: John Colani <johnacolani@gmail.com>
homepage: "https://github.com/johnhcolani"

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0







