name: auto_scroll_image
description: "Enhance your app with Auto Scroll Image for dynamic scrolling ads. Compatible with iOS, Android, macOS, and web platforms for a seamless experience on various devices "
repository: "https://github.com/johnhcolani/AutoScrollImagePackage.git"
version: 0.2.9-dev
author: John Colani <johnacolani@gmail.com>
homepage: "https://github.com/johnhcolani"

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0







